framework:
    ide: 'phpstorm://open?url=file://%%f&line=%%l'
    default_locale: 'ar_MA'
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 108000 # en secondes

    #esi: true
    #fragments: true
    php_errors:
        log: true
    #fragments:
        #hinclude_default_template: hinclude.html.twig
#    templating:
#        engines: ['twig', 'php']