sonata_user:
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group

  impersonating:
    route: sonata_admin_dashboard

#  security_acl: true
  manager_type: orm