vich_uploader:
    db_driver: orm
    mappings:
        divers_images:
            uri_prefix:         '%app.path.divers_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.divers_images%'
            namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        divers_fichiers:
            uri_prefix:         '%app.path.divers_fichiers%'
            upload_destination: '%kernel.project_dir%/public%app.path.divers_fichiers%'
            namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_remove: false  # determine whether to delete file upon removal of entity
            delete_on_update: false  # determine wheter to delete the file upon update of entity
        app_images:
            uri_prefix:         '%app.path.app_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.app_images%'
            namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        app_fichiers:
            uri_prefix:         '%app.path.app_fichiers%'
            upload_destination: '%kernel.project_dir%/public%app.path.app_fichiers%'
            namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        document_signe_convention:
            uri_prefix:         '%app.path.divers_fichiers%'
            upload_destination: '%kernel.project_dir%/public%app.path.divers_fichiers%'
            namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_remove: false  # determine whether to delete file upon removal of entity
            delete_on_update: false  # determine wheter to delete the file upon update of entity


        # divers_images:
        #     uri_prefix:         '/conventions/uploads/divers/images'
        #     upload_destination: '%kernel.project_dir%/../public_html/conventions/uploads/divers/images'
        #     namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        # divers_fichiers:
        #     uri_prefix:         '%app.path.divers_fichiers%'
        #     upload_destination: '%kernel.project_dir%/../public_html/conventions/uploads/divers/fichiers'
        #     namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        #     delete_on_remove: false  # determine whether to delete file upon removal of entity
        #     delete_on_update: false  # determine wheter to delete the file upon update of entity
        # app_images:
        #     uri_prefix:         '/conventions/uploads/divers/images'
        #     upload_destination: '%kernel.project_dir%/../public_html/conventions/uploads/divers/images'
        #     namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        # app_fichiers:
        #     uri_prefix:         '/conventions/uploads/divers/fichiers'
        #     upload_destination: '%kernel.project_dir%/../public_html/conventions/uploads/divers/fichiers'
        #     namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        # document_signe_convention:
        #     uri_prefix:         '/conventions/uploads/divers/fichiers'
        #     upload_destination: '%kernel.project_dir%/../public_html/conventions/uploads/divers/fichiers'
        #     namer:              'Vich\UploaderBundle\Naming\SmartUniqueNamer'
        #     delete_on_remove: false 
        #     delete_on_update: false             